# Generated by Django 3.0.3 on 2020-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstockdetails',
            name='costprice',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userstockdetails',
            name='currency',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userstockdetails',
            name='shortName',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='userstockdetails',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
